services:
  ollama:
    volumes:
      - ollama:/root/.ollama
    container_name: ollama
    pull_policy: always
    tty: true
    restart: unless-stopped
    image: ollama/ollama:${OLLAMA_DOCKER_TAG-latest}

  open-webui:
    build:
      context: .
      dockerfile: Dockerfile
    image: ghcr.io/open-webui/open-webui:${WEBUI_DOCKER_TAG-main}
    container_name: open-webui
    env_file:
      - .env
    volumes:
      - open-webui:/app/backend/data
    depends_on:
      - ollama
    ports:
      - ${OPEN_WEBUI_PORT-3000}:8080
    environment:
      - 'ENV=${ENV:-prod}'
      - 'ENABLE_OLLAMA_API=${ENABLE_OLLAMA_API:-false}'
      - 'OLLAMA_BASE_URL=${OLLAMA_BASE_URL:-http://ollama:11434}'
      - 'ENABLE_OPENAI_API=${ENABLE_OPENAI_API:-true}'
      - 'OPENAI_API_BASE_URL=${OPENAI_API_BASE_URL:-https://api.gpt.mws.ru/v1}'
      - 'OPENAI_API_KEY=${OPENAI_API_KEY:-}'
      - 'OPENAI_API_BASE_URLS=${OPENAI_API_BASE_URLS:-}'
      - 'OPENAI_API_KEYS=${OPENAI_API_KEYS:-}'
      - 'DEFAULT_MODELS=${DEFAULT_MODELS:-}'
      - 'TASK_MODEL=${TASK_MODEL:-}'
      - 'TASK_MODEL_EXTERNAL=${TASK_MODEL_EXTERNAL:-}'
      - 'WEBUI_SECRET_KEY=${WEBUI_SECRET_KEY:-}'
      - 'SCARF_NO_ANALYTICS=${SCARF_NO_ANALYTICS:-true}'
      - 'DO_NOT_TRACK=${DO_NOT_TRACK:-true}'
      - 'ANONYMIZED_TELEMETRY=${ANONYMIZED_TELEMETRY:-false}'
    extra_hosts:
      - host.docker.internal:host-gateway
    restart: unless-stopped

volumes:
  ollama: {}
  open-webui: {}
